<?php
/**
 * @copyright Copyright (c) 2015, Google Inc.
 * @link      https://www.google.com/recaptcha
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
require __DIR__ . '/appengine-https.php';
// Initiate the autoloader. The file should be generated by Composer.
// You will provide your own autoloader or require the files directly if you did
// not install via Composer.
require_once __DIR__ . '/../vendor/autoload.php';
// Register API keys at https://www.google.com/recaptcha/admin
$siteKey = '6Lfwjo8UAAAAAMROvA_ODI2Z9lsE6KLw8wAVZSHX';
$secret = '6Lfwjo8UAAAAAHFysn1ckGEfzpn3xm5f-TLA1rQM';
// Copy the config.php.dist file to config.php and update it with your keys to run the examples
if ($siteKey == '' && is_readable(__DIR__ . '/config.php')) {
    $config = include __DIR__ . '/config.php';
    $siteKey = $config['v3']['site'];
    $secret = $config['v3']['secret'];
}
// reCAPTCHA supports 40+ languages listed here: https://developers.google.com/recaptcha/docs/language
$lang = 'en';
?>
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,height=device-height,minimum-scale=1">
<link rel="shortcut icon" href="https://www.gstatic.com/recaptcha/admin/favicon.ico" type="image/x-icon"/>
<link rel="canonical" href="https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php">
<script type="application/ld+json">{ "@context": "http://schema.org", "@type": "WebSite", "name": "reCAPTCHA demo - Request scores", "url": "https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php" }</script>
<meta name="description" content="reCAPTCHA demo - Request scores" />
<meta property="og:url" content="https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php" />
<meta property="og:type" content="website" />
<meta property="og:title" content="reCAPTCHA demo - Request scores" />
<meta property="og:description" content="reCAPTCHA demo - Request scores" />
<link rel="stylesheet" type="text/css" href="/examples.css">
<title>reCAPTCHA demo - Request scores</title>
<header>
    <h1>reCAPTCHA demo</h1><h2>Request scores</h2>
    <p><a href="/">↤ Home</a></p>
</header>
<main>
<?php
if ($siteKey === '' || $secret === ''):
?>
    <h2>Add your keys</h2>
    <p>If you do not have keys already then visit <kbd> <a href = "https://www.google.com/recaptcha/admin">https://www.google.com/recaptcha/admin</a></kbd> to generate them. Edit this file and set the respective keys in <kbd>$siteKey</kbd> and <kbd>$secret</kbd>. Reload the page after this.</p>
    <?php
else:
    // Add the g-recaptcha tag to the form you want to include the reCAPTCHA element
    ?>
    <p>The reCAPTCHA v3 API provides a confidence score for each request.</p>
    <p><strong>NOTE:</strong>This is a sample implementation, the score returned here is not a reflection on your Google account or type of traffic. In production, refer to the distribution of scores shown in <a href="https://www.google.com/recaptcha/admin" target="_blank">your admin interface</a> and adjust your own threshold accordingly. <strong>Do not raise issues regarding the score you see here.</strong></p>
    <ol id="recaptcha-steps">
        <li class="step0">reCAPTCHA script loading</li>
        <li class="step1 hidden"><kbd>grecaptcha.ready()</kbd> fired, calling <pre>grecaptcha.execute('<?php echo $siteKey; ?>', {action: 'examples/v3scores'})'</pre></li>
        <li class="step2 hidden">Received token from reCAPTCHA service, sending to our backend with:
        <pre class="token">fetch('/recaptcha-v3-verify.php?token=abc123</pre></li>
        <li class="step3 hidden">Received response from our backend: <pre class="response">{"json": "from-backend"}</pre></li>
    </ol>
    <p><a href="/recaptcha-v3-request-scores.php">⟳ Try again</a></p>
    <script src="https://www.google.com/recaptcha/api.js?render=<?php echo $siteKey; ?>"></script>
    <script>
        const steps = document.getElementById('recaptcha-steps');
        grecaptcha.ready(function() {
            document.querySelector('.step1').classList.remove('hidden');
            grecaptcha.execute('<?php echo $siteKey; ?>', {action: 'examples/v3scores'}).then(function(token) {
                document.querySelector('.token').innerHTML = 'fetch(\'/recaptcha-v3-verify.php?action=examples/v3scores&token=\'' + token;
                document.querySelector('.step2').classList.remove('hidden');
                fetch('/recaptcha-v3-verify.php?action=examples/v3scores&token='+token).then(function(response) {
                    response.json().then(function(data) {
                        document.querySelector('.response').innerHTML = JSON.stringify(data, null, 2);
                        document.querySelector('.step3').classList.remove('hidden');
                    });
                });
            });
        });
    </script>
    <?php
endif;?>
</main>



<!-- <!DOCTYPE HTML>

<html>
	<head>
		<title>Dominic Carvalho</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<link rel="icon" href="./images/codeicon.png">
	</head>
	<body>

		<!-- Header -->
			<section id="header">
				<div class="inner">
					<span class="icon major fa-code"></span>
					<h1>Hi, I'm <strong>Dominic Carvalho</strong>, a young<br />
					aspiring developer and a BSC IT student.</h1>
					<p>I believe that I can be a good employee and a good addition to any company because I am a hard worker and I can work in a team.<br>I am a good leader that can make calculated decisions and can delegate and handle tasks accordingly.<br>I am a quick learner and will be able to adjust to the needs and requirements of the company.</p>
					<ul class="actions">
						<li><a href="#one" class="button scrolly">See more</a></li>
					</ul>
				</div>
			</section>

		<!-- One -->
			<section id="one" class="main style1">
				<div class="container">
					<div class="row 150%">
						<div class="6u 12u$(medium)">
							<header class="major">
								<h2>About me</h2>
							</header>
							<p>I'm 24 years old and I am currently working as an intermediate developer at Digital Outsource Services in century city Cape Town whilst finishing my last module for my Bachelor of Science in Information Technology. I am also one of 3 directors in a startup development company where we aim to create beautiful cutting edge software solutions. I enjoy being active and I like to stay fit. Furthermore, I am passionate about expanding my knowledge and tackling challenges that will enhance my skills and keep me up to date with the exciting Development industry.</p>
						</div>
						<div class="6u$ 12u$(medium) important(medium)">
							<span class="image fit"><img src="images/domz.png" alt="" /></span>
						</div>
					</div>
				</div>
			</section>

		<!-- Two -->
			<section id="two" class="main style2">
				<div class="container">
					<div class="row 150%">
						<div class="6u 12u$(medium)">
							<ul class="major-icons">
								<li><span class="icon style1 major fa-laptop"></span></li>
								<li><span class="icon style2 major fa-code"></span></li>
								<li><span class="icon style3 major fa-mobile"></span></li>
								<li><span class="icon style4 major fa-cog"></span></li>
								<li><span class="icon style5 major fa-desktop"></span></li>
								<li><span class="icon style6 major fa-cloud"></span></li>
							</ul>
						</div>
						<div class="6u$ 12u$(medium)">
							<header class="major">
								<h2>My expereince</h2>
							</header>
							<p> <strong>My Studies</strong><br>During my studies I have not only learned a lot but I have practically applied my knowledge to assignments and projects for the university.</p>

							<p> <strong>Digital Outsource Servcies</strong><br>I am currently working as an Intermediate Developer in a fast paced company in Century City. We work in an ever changing market which means our tech stack is dynamic and always being altered to best suit the problem at hand.</p>

							<p><strong>Internship</strong><br>In the beginning of my journey I had an innternship at a company called Unomena that does web developement, design and hosting where I was trained in areas like backend development( Using python on Django ), Frontend( Using the bootstrap framework ), Project management( Where I learned how to work with and use Jirra and Github ) and System admin( Where I learned how to deploy using Gunicorn,Nginx and how to configure and work with the linux, mac and windows terminal ). My Internship was greatly beneficial and I participated and worked in many projects</p>

							<p><strong>Edge Case Development</strong><br>I am currently 1 of three Directors in a company called Edge Case Development where myself and two friends felt the need and saw the opportunity to start our own Development company where we can use our creativity to design and develop our own websites at affordable prices.</p>
						</div>
					</div>
				</div>
			</section>

		<!-- Three -->
			<section id="three" class="main style1 special">
				<div class="container">
					<header class="major">
						<h2>My work</h2>
					</header>
					<p>Below are two projects that have recently been completed by myself together with my classmates and work colleagues.</p>
					<div class="row 150%">
						<div class="4u 12u$(medium)">
							<span class="image fit"><img src="images/hectic.jpg" alt="" /></span>
							<h3>Github</h3>
							<p>I'm always trying to learn new things and play with the latest ES6 features.</p>
							<ul class="actions">
								<li><a href="https://github.com/Domz444" target="_blank" class="button">Github Link</a></li>
							</ul>
						</div>
						<div class="4u 12u$(medium)">
							<span class="image fit"><img src="images/code.png" alt="" /></span>
							<h3>Edge Case Development</h3>
							<p>Here's a link to Edge Case Developments site where you will find out about what we do.</p>
							<ul class="actions">
								<li><a href="http://edgecasedevelopment.co.za/main.html" target="_blank" class="button">View Project</a></li>
							</ul>
						</div>
						<div class="4u$ 12u$(medium)">
							<span class="image fit"><img src="images/edge.jpg" alt="" /></span>
							<h3>Impremium Imports</h3>
							<p>An alcohol importing company based in Texas called Impremium Imports.</p>
							<ul class="actions">
								<li><a href="http://impremiumimports.com/" target="_blank" class="button">View Project</a></li>
							</ul>
						</div>
					</div>
				</div>
			</section>

		<!-- Four -->
			<section id="four" class="main style2 special">
				<div class="container">
					<header class="major">
						<h2>Contact Me</h2>
					</header>
					<p></p>
					<ul class="actions uniform">
						<li>Domz.Carvalho@gmail.com</li>
						<li>079-849-8771</li>
					</ul>

				</div>
			</section>

		<!-- Footer -->
			<section id="footer">
				<ul class="icons">
					<li><a href="https://www.facebook.com/dominic.carvalho.7" class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="https://www.instagram.com/dominiccarvalho4/" class="icon alt fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="mailto:Domz.Carvalho@gmail.com" class="icon alt fa-envelope"><span class="label">Email</span></a></li>
					<li><a href="https://za.linkedin.com/in/dominic-carvalho-464b71120
					" class="icon alt fa-linkedin"><span class="label">Email</span></a></li>
				</ul>
				<ul class="copyright">
					<li>&copy; Dominic Carvalho</li><li>Developer</li>
				</ul>
			</section>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html> -->
